-- COLUNAS NECESSÁRIAS ---> DATA_VENDA(YEAR), SABOR, QTD MAIS VENDIDO PARA O MENOS VENDIDO
SELECT * FROM TABELA_DE_CLIENTES

SELECT * FROM NOTAS_FISCAIS

SELECT * FROM ITENS_NOTAS_FISCAIS

SELECT * FROM TABELA_DE_PRODUTOS


SELECT 
TP.SABOR AS SABOR,
YEAR(NF.DATA_VENDA) AS VENDAS_ANO,
SUM(INF.QUANTIDADE) AS QTD
FROM TABELA_DE_CLIENTES TC
	JOIN NOTAS_FISCAIS NF
	ON TC.CPF = NF.CPF
	JOIN ITENS_NOTAS_FISCAIS INF
	ON INF.NUMERO = NF.NUMERO
	JOIN TABELA_DE_PRODUTOS TP
	ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
GROUP BY TP.SABOR,
YEAR(NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC

SELECT 
	TP.SABOR AS SABOR,
	YEAR(NF.DATA_VENDA) AS ANO,
	SUM(INF.QUANTIDADE) AS QTD
FROM NOTAS_FISCAIS NF 
	JOIN ITENS_NOTAS_FISCAIS INF
	ON INF.NUMERO = NF.NUMERO
	JOIN TABELA_DE_PRODUTOS TP
	ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
WHERE YEAR(NF.DATA_VENDA) = '2015'
GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC

SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QTD_ANO
FROM NOTAS_FISCAIS NF
JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2015
GROUP BY YEAR(NF.DATA_VENDA)

SELECT 
	VS.SABOR, VS.ANO, VS.QTD, VA.QTD_ANO
FROM(
	SELECT 
		TP.SABOR AS SABOR,
		YEAR(NF.DATA_VENDA) AS ANO,
		SUM(INF.QUANTIDADE) AS QTD
	FROM NOTAS_FISCAIS NF 
		JOIN ITENS_NOTAS_FISCAIS INF
		ON INF.NUMERO = NF.NUMERO
		JOIN TABELA_DE_PRODUTOS TP
		ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
	WHERE YEAR(NF.DATA_VENDA) = '2015'
	GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)
	
) VS
JOIN(
	SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QTD_ANO
	FROM NOTAS_FISCAIS NF
	JOIN ITENS_NOTAS_FISCAIS INF
	ON NF.NUMERO = INF.NUMERO
	WHERE YEAR(NF.DATA_VENDA) = 2015
	GROUP BY YEAR(NF.DATA_VENDA)
) VA
ON VS.ANO = VA.ANO
ORDER BY VS.QTD DESC

SELECT 
	VS.SABOR, VS.ANO, VS.QTD, VA.QTD_ANO,
	( (VS.QTD/VA.QTD_ANO) * 100) AS PERCENTUAL
FROM(
	SELECT 
		TP.SABOR AS SABOR,
		YEAR(NF.DATA_VENDA) AS ANO,
		SUM(INF.QUANTIDADE) AS QTD
	FROM NOTAS_FISCAIS NF 
		JOIN ITENS_NOTAS_FISCAIS INF
		ON INF.NUMERO = NF.NUMERO
		JOIN TABELA_DE_PRODUTOS TP
		ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
	WHERE YEAR(NF.DATA_VENDA) = '2015'
	GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)
	
) VS
JOIN(
	SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QTD_ANO
	FROM NOTAS_FISCAIS NF
	JOIN ITENS_NOTAS_FISCAIS INF
	ON NF.NUMERO = INF.NUMERO
	WHERE YEAR(NF.DATA_VENDA) = 2015
	GROUP BY YEAR(NF.DATA_VENDA)
) VA
ON VS.ANO = VA.ANO
ORDER BY VS.QTD DESC

SELECT 
	VS.SABOR, VS.ANO, VS.QTD, 
	( ( CONVERT(FLOAT, VS.QTD) / CONVERT( FLOAT, VA.QTD_ANO) ) * 100) AS PERCENTUAL
FROM(
	SELECT 
		TP.SABOR AS SABOR,
		YEAR(NF.DATA_VENDA) AS ANO,
		SUM(INF.QUANTIDADE) AS QTD
	FROM NOTAS_FISCAIS NF 
		JOIN ITENS_NOTAS_FISCAIS INF
		ON INF.NUMERO = NF.NUMERO
		JOIN TABELA_DE_PRODUTOS TP
		ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
	WHERE YEAR(NF.DATA_VENDA) = '2015'
	GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)
	
) VS
JOIN(
	SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QTD_ANO
	FROM NOTAS_FISCAIS NF
	JOIN ITENS_NOTAS_FISCAIS INF
	ON NF.NUMERO = INF.NUMERO
	WHERE YEAR(NF.DATA_VENDA) = 2015
	GROUP BY YEAR(NF.DATA_VENDA)
) VA
ON VS.ANO = VA.ANO
ORDER BY VS.QTD DESC

SELECT 
	VS.SABOR, VS.ANO, VS.QTD, 
	ROUND( ( CONVERT(FLOAT, VS.QTD) / CONVERT( FLOAT, VA.QTD_ANO) ) * 100,2) AS PERCENTUAL
FROM(
	SELECT 
		TP.SABOR AS SABOR,
		YEAR(NF.DATA_VENDA) AS ANO,
		SUM(INF.QUANTIDADE) AS QTD
	FROM NOTAS_FISCAIS NF 
		JOIN ITENS_NOTAS_FISCAIS INF
		ON INF.NUMERO = NF.NUMERO
		JOIN TABELA_DE_PRODUTOS TP
		ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
	WHERE YEAR(NF.DATA_VENDA) = '2015'
	GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)
	
) VS
JOIN(
	SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QTD_ANO
	FROM NOTAS_FISCAIS NF
	JOIN ITENS_NOTAS_FISCAIS INF
	ON NF.NUMERO = INF.NUMERO
	WHERE YEAR(NF.DATA_VENDA) = 2015
	GROUP BY YEAR(NF.DATA_VENDA)
) VA
ON VS.ANO = VA.ANO
ORDER BY VS.QTD DESC

SELECT 
	 VS.TAMANHO, VS.ANO, VS.QTD,
	ROUND( ( CONVERT(FLOAT, VS.QTD) / CONVERT( FLOAT, VA.QTD_ANO) ) * 100,2) AS PERCENTUAL
FROM(
	SELECT 
		TP.TAMANHO,
		YEAR(NF.DATA_VENDA) AS ANO,
		SUM(INF.QUANTIDADE) AS QTD
	FROM NOTAS_FISCAIS NF 
		JOIN ITENS_NOTAS_FISCAIS INF
		ON INF.NUMERO = NF.NUMERO
		JOIN TABELA_DE_PRODUTOS TP
		ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
	WHERE YEAR(NF.DATA_VENDA) = '2016'
	GROUP BY YEAR(NF.DATA_VENDA),TP.TAMANHO
	
) VS
JOIN(
	SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QTD_ANO
	FROM NOTAS_FISCAIS NF
	JOIN ITENS_NOTAS_FISCAIS INF
	ON NF.NUMERO = INF.NUMERO
	WHERE YEAR(NF.DATA_VENDA) = '2016'
	GROUP BY YEAR(NF.DATA_VENDA)
) VA
ON VS.ANO = VA.ANO
ORDER BY VS.QTD DESC

SELECT
VS.TAMANHO, VS.ANO, VS.VENDA_ANO,
ROUND((CONVERT( FLOAT, VS.VENDA_ANO) / CONVERT( FLOAT, VA.VENDA_TOTAL_ANO)) * 100, 2) AS PERCENTUAL
FROM 
(
SELECT
TP.TAMANHO
,YEAR(NF.DATA_VENDA) AS ANO
,SUM(INF.QUANTIDADE) AS VENDA_ANO
FROM TABELA_DE_PRODUTOS TP
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF
ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY TP.TAMANHO, YEAR(NF.DATA_VENDA)
) VS
INNER JOIN
(
SELECT 
YEAR(NF.DATA_VENDA) AS ANO
, SUM(INF.QUANTIDADE) AS VENDA_TOTAL_ANO
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY YEAR(NF.DATA_VENDA)
) VA
ON VS.ANO = VA.ANO
ORDER BY VS.VENDA_ANO DESC;