
SELECT * FROM TABELA_DE_CLIENTES;

SELECT CPF,NOME,BAIRRO, ESTADO FROM TABELA_DE_CLIENTES;

SELECT CPF AS ID ,NOME AS Cliente ,BAIRRO, ESTADO as UF FROM TABELA_DE_CLIENTES;

SELECT TDC.CPF AS ID ,TDC.NOME AS Cliente ,TDC.BAIRRO, TDC.ESTADO as UF FROM TABELA_DE_CLIENTES TDC;

SELECT TABELA_DE_CLIENTES.CPF , TABELA_DE_CLIENTES.BAIRRO , TABELA_DE_CLIENTES.NOME FROM TABELA_DE_CLIENTES;