
select distinct bairro from TABELA_DE_CLIENTES;
-- 12 BAIRROS RELACIONADOS A CLIENTES

SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
-- 4 BAIRROS RELACIONADOS A VENDEDORES



select distinct bairro from TABELA_DE_CLIENTES
UNION 
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

select distinct bairro , 'CLIENTE' AS ORIGEM from TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO, 'VENDEDORES' AS ORIGEM FROM TABELA_DE_VENDEDORES;

select distinct bairro , 'CLIENTE' AS ORIGEM from TABELA_DE_CLIENTES
UNION 
SELECT DISTINCT BAIRRO, 'VENDEDORES' AS ORIGEM FROM TABELA_DE_VENDEDORES;



