
SELECT * FROM TABELA_DE_VENDEDORES;

SELECT * FROM NOTAS_FISCAIS;

SELECT MATRICULA , COUNT(*) NUMERO_VENDAS FROM NOTAS_FISCAIS
GROUP BY MATRICULA;

SELECT TV.NOME , COUNT(*) NUMERO_VENDAS FROM TABELA_DE_VENDEDORES TV
INNER JOIN  NOTAS_FISCAIS NF
ON NF.MATRICULA = TV.MATRICULA
GROUP BY TV.NOME;

/* DESAFIO
Dito isso, e levando em consideração os comandos da consulta, 
desejamos que na resposta desta consulta apareça não somente 
o código do produto, mas também o nome do produto. */

SELECT  TP.CODIGO_DO_PRODUTO,TP.NOME_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS IFN
INNER JOIN TABELA_DE_PRODUTOS TP 
ON TP.CODIGO_DO_PRODUTO = IFN.CODIGO_DO_PRODUTO
GROUP BY TP.CODIGO_DO_PRODUTO , TP.NOME_DO_PRODUTO
HAVING SUM(QUANTIDADE) > 394000 
ORDER BY SUM(QUANTIDADE) DESC;


