CREATE VIEW MEDIA_EMBALAGENS AS 
SELECT EMBALAGEM, ROUND(AVG(PRECO_DE_LISTA),2) AS PRECO_MEDIO FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM

SELECT * FROM MEDIA_EMBALAGENS
WHERE MEDIA_EMBALAGENS.PRECO_MEDIO < 10


CREATE VIEW QUANTIDADE_POR_PRODUTO AS 
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO 

SELECT * FROM QUANTIDADE_POR_PRODUTO 
WHERE QUANTIDADE_POR_PRODUTO.QUANTIDADE > 394000
ORDER BY QUANTIDADE DESC;
