
SELECT * FROM TABELA_DE_CLIENTES;

SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES;

SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES
ORDER BY CIDADE, IDADE;

SELECT CIDADE, SUM(IDADE) AS IDADE FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

SELECT CIDADE, SUM(IDADE) AS IDADE, SUM(LIMITE_DE_CREDITO) CREDITO FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

SELECT CIDADE, AVG(IDADE) AS IDADE, ROUND(AVG(LIMITE_DE_CREDITO),2) CREDITO FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

SELECT CIDADE, COUNT(*) NUMERO_CLIENTES FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

SELECT EMBALAGEM, COUNT(*) NUMERO_PRODUTOS FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'LARANJA'
GROUP BY EMBALAGEM

SELECT CODIGO_DO_PRODUTO,COUNT(*) FROM ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99
GROUP BY CODIGO_DO_PRODUTO
