
SELECT * FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MANGA' AND TAMANHO = '470 ML';

SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MANGA' OR TAMANHO = '470 ML';

SELECT * FROM TABELA_DE_PRODUTOS
WHERE not(SABOR = 'MANGA' AND TAMANHO = '470 ML');

SELECT * FROM TABELA_DE_PRODUTOS
WHERE NOT(SABOR = 'MANGA' OR TAMANHO = '470 ML');

SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'mANGA' OR SABOR = 'LARANJA' OR SABOR = 'MELANCIA';

SELECT * FROM TABELA_DE_PRODUTOS
WHERE (SABOR IN('MANGA','LARANJA' ,'MELANCIA')) AND TAMANHO = '1 LITRO';

SELECT * FROM TABELA_DE_CLIENTES
WHERE CIDADE IN ('RIO DE JANEIRO', 'SAO PAULO');

SELECT * FROM TABELA_DE_CLIENTES
WHERE (CIDADE IN ('RIO DE JANEIRO', 'SAO PAULO')) AND IDADE > 20;

SELECT * FROM TABELA_DE_CLIENTES
WHERE (CIDADE IN ('RIO DE JANEIRO', 'SAO PAULO')) AND (IDADE >= 20 AND IDADE <= 25);

SELECT * FROM TABELA_DE_CLIENTES
WHERE (CIDADE IN ('RIO DE JANEIRO', 'SAO PAULO')) AND (IDADE BETWEEN 20 AND 25);