
SELECT * FROM TABELA_DE_CLIENTES

SELECT * FROM NOTAS_FISCAIS

SELECT * FROM ITENS_NOTAS_FISCAIS

SELECT TC.NOME AS CLIENTE, NF.DATA_VENDA ,
TC.VOLUME_DE_COMPRA AS QUANTIDADE_DE_COMPRA_ESPERADO, SUM( INF.QUANTIDADE) AS QUANTIDADE_REAL_DE_COMPRA
FROM TABELA_DE_CLIENTES TC
JOIN NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF
JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY TC.NOME, TC.VOLUME_DE_COMPRA, NF.DATA_VENDA


SELECT TC.NOME AS CLIENTE, 
CONVERT(VARCHAR(7),NF.DATA_VENDA, 120) AS MES_ANO,
TC.VOLUME_DE_COMPRA AS QTD_ESPERADO, 
SUM(INF.QUANTIDADE) AS QTD_REAL,
(CASE
WHEN SUM(INF.QUANTIDADE) > TC.VOLUME_DE_COMPRA THEN 'Limite estourado'
when SUM(INF.QUANTIDADE) < TC.VOLUME_DE_COMPRA THEN 'Dentro do limite'
else ''
END) as LIMITE
FROM TABELA_DE_CLIENTES TC
JOIN NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF
JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY TC.NOME, TC.VOLUME_DE_COMPRA, CONVERT(VARCHAR(7),NF.DATA_VENDA, 120)


SELECT TC.NOME AS CLIENTE, 
	CONVERT(VARCHAR(7),NF.DATA_VENDA, 120) AS MES_ANO,
	TC.VOLUME_DE_COMPRA AS QTD_ESPERADO, 
	SUM(INF.QUANTIDADE) AS QTD_REAL,
	(CASE
		WHEN SUM(INF.QUANTIDADE) > TC.VOLUME_DE_COMPRA THEN 'Limite estourado'
		else 'Dentro do limite'
	END) as LIMITE
FROM TABELA_DE_CLIENTES TC
		JOIN NOTAS_FISCAIS NF
		ON TC.CPF = NF.CPF
		JOIN ITENS_NOTAS_FISCAIS INF
		ON NF.NUMERO = INF.NUMERO
WHERE CONVERT(VARCHAR(7),NF.DATA_VENDA, 120) = '2015-01'
GROUP BY TC.NOME, TC.VOLUME_DE_COMPRA, CONVERT(VARCHAR(7),NF.DATA_VENDA, 120)

SELECT TC.NOME AS CLIENTE, 
	CONVERT(VARCHAR(7),NF.DATA_VENDA, 120) AS MES_ANO,
	TC.VOLUME_DE_COMPRA AS QTD_ESPERADO, 
	SUM(INF.QUANTIDADE) AS QTD_REAL,
	(CASE
		WHEN SUM(INF.QUANTIDADE) > TC.VOLUME_DE_COMPRA THEN 'Limite estourado'
		else 'Dentro do limite'
	END) as LIMITE,
	(TC.VOLUME_DE_COMPRA - SUM(INF.QUANTIDADE)) AS DIFERENCA,
	ROUND( ( 1- ( TC.VOLUME_DE_COMPRA / SUM(INF.QUANTIDADE) ) ) * 100 ,2) AS PERCENTUAL
FROM TABELA_DE_CLIENTES TC
		JOIN NOTAS_FISCAIS NF
		ON TC.CPF = NF.CPF
		JOIN ITENS_NOTAS_FISCAIS INF
		ON NF.NUMERO = INF.NUMERO
WHERE CONVERT(VARCHAR(7),NF.DATA_VENDA, 120) = '2015-01'
GROUP BY TC.NOME, TC.VOLUME_DE_COMPRA, CONVERT(VARCHAR(7),NF.DATA_VENDA, 120)
HAVING SUM(INF.QUANTIDADE) > TC.VOLUME_DE_COMPRA