
SELECT GETDATE() AS DATAHOJE;

SELECT DATEADD(DAY, 10, GETDATE()) AS DATA10DIAS

SELECT GETDATE() AS DATAHOJE, DATEADD(DAY, 10, GETDATE()) AS DATA10DIAS, DATEADD(DAY, -48, GETDATE()) AS DATA_48_DIAS_ATRAS

SELECT GETDATE() AS DATAHOJE, 
DATEADD(DAY, 10, GETDATE()) AS DATA10DIAS, 
DATEADD(DAY, -48, GETDATE()) AS DATA_48_DIAS_ATRAS,
DATEDIFF(DAY,'2025-01-01',GETDATE()) AS DIAS_DESDE_INICIO_ANO

SELECT GETDATE() AS DATAHOJE, 
DATEADD(DAY, 10, GETDATE()) AS DATA10DIAS, 
DATEADD(DAY, -48, GETDATE()) AS DATA_48_DIAS_ATRAS,
DATEDIFF(DAY,'2025-01-01',GETDATE()) AS DIAS_DESDE_INICIO_ANO

SELECT DATEPART(DAY, GETDATE()) AS DIA_HOJE

SELECT ISDATE('2025-08-31')



select NOME + ' Nasceu ' +DATENAME(WEEKDAY, DATA_DE_NASCIMENTO) + 
' no dia ' + DATENAME(DAY, DATA_DE_NASCIMENTO) +
' no mês ' + DATENAME(MONTH, DATA_DE_NASCIMENTO) +
' do ano ' + DATENAME(YEAR,DATA_DE_NASCIMENTO) 
from TABELA_DE_CLIENTES