
SELECT COUNT(*) FROM TABELA_DE_CLIENTES;
-- 16 CLIENTES ---> 7 CLIENTES POSSUEM VENDEDORES EM SEUS BAIRROS

SELECT COUNT(*) FROM TABELA_DE_VENDEDORES;
-- 4 VENDEDORES ---> 3 VENDEDORES POSSUEM EM SEUS BAIRROS CLIENTES


SELECT DISTINCT TV.NOME AS NOME_VENDEDOR , TV.BAIRRO AS BAIRRO_VENDEDOR,TC.BAIRRO AS BAIRRO_CLIENTE ,TC.NOME AS NOME_CLIENTE
FROM TABELA_DE_CLIENTES TC
INNER JOIN TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO


-- QUAL VENDEDOR NÃO TEM CLIENTE EM SEU BAIRRO?

SELECT DISTINCT TV.NOME AS NOME_VENDEDOR , TV.BAIRRO AS BAIRRO_VENDEDOR,TC.BAIRRO AS BAIRRO_CLIENTE ,TC.NOME AS NOME_CLIENTE
FROM TABELA_DE_CLIENTES TC
RIGHT JOIN TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TC.BAIRRO IS NULL

-- QUAL VENDEDOR NÃO TEM CLIENTE EM SEU BAIRRO? ---> ROBERTA MARTINS EM COPACABANA


-- QUAIS CLIENTES NÃO TÊM VENDEDOR EM SEU BAIRRO?

SELECT DISTINCT TV.NOME AS NOME_VENDEDOR , TV.BAIRRO AS BAIRRO_VENDEDOR,TC.BAIRRO AS BAIRRO_CLIENTE ,TC.NOME AS NOME_CLIENTE
FROM TABELA_DE_CLIENTES TC
LEFT JOIN TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TV.BAIRRO IS NULL

-- QUAIS CLIENTES NÃO TÊM VENDEDOR EM SEU BAIRRO? ---> 9 CLIENTES
/*Fernando Cavalcante
Juliana Silva
Fabio Carvalho
Marcelo Mattos
Edson Meilelles
Abel Silva 
Marcos Nogueira
Petra Oliveira
Walber Lontra*/


SELECT DISTINCT TV.NOME AS NOME_VENDEDOR , TV.BAIRRO AS BAIRRO_VENDEDOR,TC.BAIRRO AS BAIRRO_CLIENTE ,TC.NOME AS NOME_CLIENTE
FROM TABELA_DE_CLIENTES TC
FULL JOIN TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TC.BAIRRO IS NULL OR TV.BAIRRO IS NULL

