
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MANGA';

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA, 
(CASE  
	when PRECO_DE_LISTA > 12 THEN 'PRODUTO CARO'
	when PRECO_DE_LISTA > 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	else 'PRODUTO BARATO'
END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MANGA'
ORDER BY PRECO_DE_LISTA ;

SELECT 
(CASE  
	when PRECO_DE_LISTA > 12 THEN 'PRODUTO CARO'
	when PRECO_DE_LISTA > 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	else 'PRODUTO BARATO'
END) AS CLASSIFICACAO, 
COUNT(*) AS NUMERO_PRODUTOS
FROM TABELA_DE_PRODUTOS
GROUP BY CLASSIFICACAO
ORDER BY PRECO_DE_LISTA 
;

SELECT 
(CASE  
	when PRECO_DE_LISTA > 12 THEN 'PRODUTO CARO'
	when PRECO_DE_LISTA > 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	else 'PRODUTO BARATO'
END) AS CLASSIFICACAO, 
COUNT(*) AS NUMERO_PRODUTOS
FROM TABELA_DE_PRODUTOS
GROUP BY (CASE when PRECO_DE_LISTA > 12 THEN 'PRODUTO CARO'
	when PRECO_DE_LISTA > 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	else 'PRODUTO BARATO' END);


SELECT (CASE 
	WHEN LIMITE_DE_CREDITO > 150000 THEN 'CLIENTE GRANDE'
	WHEN LIMITE_DE_CREDITO >= 110000 AND LIMITE_DE_CREDITO < 150000 THEN 'CLIENTE MEDIO'
	ELSE 'CLIENTE PEQUENO'
END) AS CLASSIFICACAO
FROM TABELA_DE_CLIENTES
ORDER BY (CASE 
	WHEN LIMITE_DE_CREDITO > 150000 THEN 'CLIENTE GRANDE'
	WHEN LIMITE_DE_CREDITO >= 110000 AND LIMITE_DE_CREDITO < 150000 THEN 'CLIENTE MEDIO'
	ELSE 'CLIENTE PEQUENO'
END);