
SELECT CONVERT(VARCHAR(50),GETDATE(),103)

SELECT CONVERT(VARCHAR(50),GETDATE(),121)

SELECT * FROM TABELA_DE_CLIENTES;

SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(35),DATA_DE_NASCIMENTO,111) 
FROM TABELA_DE_CLIENTES;

SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(35),DATA_DE_NASCIMENTO,106) 
FROM TABELA_DE_CLIENTES;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA FROM TABELA_DE_PRODUTOS;


SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é: ',PRECO_DE_LISTA) as PRECO FROM TABELA_DE_PRODUTOS;


SELECT * FROM TABELA_DE_CLIENTES;

SELECT * FROM ITENS_NOTAS_FISCAIS

SELECT * FROM NOTAS_FISCAIS

SELECT 
CONCAT('O cliente ', TC.NOME, ' comprou ', 'R$ ', (INF.PRECO * INF.QUANTIDADE), ' no ano de ', YEAR(NF.DATA_VENDA))
FROM TABELA_DE_CLIENTES TC
JOIN NOTAS_FISCAIS NF 
ON TC.CPF = NF.CPF
JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO