
SELECT EMBALAGEM, ROUND(AVG(PRECO_DE_LISTA),2) AS PRECO_MEDIO FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

SELECT EMBALAGEM, ROUND(AVG(PRECO_DE_LISTA),2) AS PRECO_MEDIO FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM
HAVING ROUND(AVG(PRECO_DE_LISTA),2) <= 10;


SELECT MEDIA_EMBALAGENS.EMBALAGEM, MEDIA_EMBALAGENS.PRECO_MEDIO FROM 
(SELECT EMBALAGEM, ROUND(AVG(PRECO_DE_LISTA),2) AS PRECO_MEDIO FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM) MEDIA_EMBALAGENS
WHERE MEDIA_EMBALAGENS.PRECO_MEDIO <= 10;


SELECT TOP_PRODUTOS.CODIGO_DO_PRODUTO, TOP_PRODUTOS.NOME_DO_PRODUTO, TOP_PRODUTOS.QUANTIDADE 
FROM (
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO
) TOP_PRODUTOS
WHERE TOP_PRODUTOS.QUANTIDADE > 394000
ORDER BY TOP_PRODUTOS.QUANTIDADE DESC;

